# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
  schedule:
    - cron: "45 5 * * *"
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - run: flyctl deploy --remote-only --config fly-danger.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_DANGER_API_TOKEN }}
